"""empty message

Revision ID: 93b85194487c
Revises: 7089862da2ea
Create Date: 2022-02-06 01:10:46.226107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93b85194487c'
down_revision = '7089862da2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_selection', sa.Column('blog_url', sa.String(), nullable=False))
    op.add_column('blog_selection', sa.Column('user_id', sa.String(), nullable=False))
    op.add_column('blog_selection', sa.Column('is_selected', sa.Boolean(), nullable=True))
    op.add_column('blog_selection', sa.Column('article_selectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('blog_selection', 'userId')
    op.drop_column('blog_selection', 'blogUrl')
    op.drop_column('blog_selection', 'isSelected')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_selection', sa.Column('isSelected', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blog_selection', sa.Column('blogUrl', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('blog_selection', sa.Column('userId', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('blog_selection', 'article_selectors')
    op.drop_column('blog_selection', 'is_selected')
    op.drop_column('blog_selection', 'user_id')
    op.drop_column('blog_selection', 'blog_url')
    # ### end Alembic commands ###
